name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CI_NIX_FLAKE: .#default
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Lint
        run: |
          nix develop ${{ env.CI_NIX_FLAKE }} --command \
            editorconfig-checker && echo "ok"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Cache Go
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-go-${{ hashfiles('go.mod', 'go.sum') }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
      - name: Test
        run: |
          nix develop ${{ env.CI_NIX_FLAKE }} --command \
            go test -v -cover -race ./...
